version: '3.5'
services:
  testapp:
    image: node
    volumes:
      - ../testapp:/testapp
    entrypoint: ["/bin/sh", "-c", "cd /testapp && npm install -g chai chai-http mocha && mocha index.js"]
    networks:
      - devops
networks:
  devops:
    external: true